name-template: "Release $RESOLVED_VERSION"
tag-template: "$RESOLVED_VERSION"

# í•´ë‹¹ ë¼ë²¨ì´ ë¶™ì€ prì€ ë³€ê²½ë‚´ìš©ì— ì¶”ê°€ ì•ˆí•¨.
exclude-labels:
  - 'skip'

# ê° prì˜ ë¼ë²¨ì— ë”°ë¼ì„œ ì¹´í…Œê³ ë¦¬ê°€ ë‚˜ë‰¨.
categories:
  - title: 'ğŸš€ Features'
    label: 'features'
  - title: 'ğŸ›  Modify'
    label: 'modify'
  - title: 'ğŸ”¥ Hotfix'
    label: 'hotfix'

#  ê° prì˜ ë‚´ìš© ì„¤ëª… ë’¤ì— ì¶”ê°€ë  ì •ë³´. ì•„ë˜ì™€ ê°™ì€ í˜•íƒœë¡œ ì•Œë§ì€ ì¹´í…Œê³ ë¦¬ì— ë¬¸ì¥ì´ ì¶”ê°€ë¨.
#  - prì œëª© @prì˜¬ë¦°ì‚¬ëŒID (#prë²ˆí˜¸)
change-template: '- $TITLE @$AUTHOR (#$NUMBER) '

# ì¹´í…Œê³ ë¦¬ ë¶„ë¥˜ê°€ ì•ˆë˜ëŠ” prì€ Uncategorized íƒ€ì´í‹€ë¡œ ë¶„ë¥˜.
# ì—¬ê¸°ì„œ $CHANGESëŠ” í•´ë‹¹ PRì˜ ì œëª©ì„.
template: |
  ## Uncategorized
  $CHANGES

# ê° prì˜ ë¼ë²¨ì— ë”°ë¼ì„œ ë²„ì „ ì—… ê¸°ì¤€ì´ ë‹¬ë¼ì§.
version-resolver:
  major:
    labels:
      - "features"
  minor:
    labels:
      - "modify"
  default: patch